# Define que es un servicio web
type: web
# Especifica el lenguaje y entorno
build:
  env: java
# Comando de build para Maven
prebuild:
  - export JAVA_HOME=/opt/render/project/.jdk
  - ./mvnw clean install
start:
  - java -jar target/*.jar